name: CMake

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally
    # well on Windows or Mac.  You can convert this to a matrix build if you need
    # cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: windows-latest

    steps:
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: install 7zip
      run: pacman -Sy --noconfirm --noprogressbar --needed p7zip

    - name: install git
      run: pacman -Sy --noconfirm --noprogressbar --needed p7zip

    - uses: actions/checkout@v2

    - name: Debugging with tmate
      uses: mxschmitt/action-tmate@v3.1
      with:
        sudo: false
